# CosmicBroAI/scripts/init_cosmic_bro2.py
# Clean + efficient trait pipeline for Carnal2.0

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import json
import re
from pathlib import Path

# ---------------------------
# 1) MODEL INIT
# ---------------------------
MODEL_PATH = "CosmicBroAI/scripts/init_cosmic_bro2"  # change if you host elsewhere
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
model = AutoModelForCausalLM.from_pretrained(MODEL_PATH)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# ---------------------------
# 2) TRAIT CLEANING UTILITIES
# ---------------------------

COMMON_FIXES = {
    "Visulization": "Visualization",
    "Alchemistry": "Alchemy",
    "precedentTransactions": "PrecedentTransactions",
    "TarotAstral": "TarotAstralWork",
    "Masculine Signs": "MasculineSigns",
    "Feminine Signs": "FeminineSigns",
    "TeleportationTraining": "TelekinesisTraining",  # if it appears as a slip
}

def camelize(s: str) -> str:
    # keep alphanum + spaces, replace separators with space
    s = re.sub(r"[_\-]+", " ", s)
    s = re.sub(r"[^\w\s]", " ", s)          # remove non-word except space
    s = re.sub(r"\s+", " ", s).strip()
    # TitleCase then remove spaces
    parts = s.title().split()
    return "".join(parts)

def normalize_item(raw: str) -> str:
    if not raw:
        return ""
    s = raw.strip().strip(",;")
    # drop list numbers like "17. StockScreener"
    s = re.sub(r"^\d+\.\s*", "", s)
    # remove stray asterisks
    s = s.replace("*", "")
    # quick common fixes before camel
    for bad, good in COMMON_FIXES.items():
        if bad in s:
            s = s.replace(bad, good)
    # final CamelCase
    s = camelize(s)
    return s

def clean_list(raw_blob: str) -> list:
    # split by commas and newlines, clean each
    rough = re.split(r"[,|\n]", raw_blob)
    cleaned = []
    seen = set()
    for chunk in rough:
        item = normalize_item(chunk)
        if not item:
            continue
        key = item.lower()
        if key not in seen:
            seen.add(key)
            cleaned.append(item)
    # sort for stable, pretty output
    cleaned.sort()
    return cleaned

def write_outputs(namespace: dict, out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    # JSON dump
    with (out_dir / "traits_clean.json").open("w", encoding="utf-8") as f:
        json.dump(namespace, f, ensure_ascii=False, indent=2)
    # Python module
    py_path = out_dir / "traits_clean.py"
    with py_path.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by init_cosmic_bro.py\n\n")
        for name, arr in namespace.items():
            f.write(f"{name} = [\n")
            for v in arr:
                f.write(f'    "{v}",\n')
            f.write("]\n\n")

# ---------------------------
# 3) PASTE YOUR RAW BLOCKS HERE (messy is fine)
# ---------------------------

RAW_MYSTICMIND = """
PsychicAbilities, Telepathy, Clairvoyance, Clairaudience, Clairsentience, Precognition, Retrocognition,
Psychokinesis, Telekinesis, Levitation, AstralProjection, OutOfBodyExperience, IntuitionDevelopment**,
EmpathicAbilities, EnergyHealing, Reiki, Meditation, Visualization, Mindfulness, CosmicConsciousness,
UniversalAwareness, SpiritualGrowth, KarmaAwareness, ReincarnationBeliefs, PastLifeRegression,
LifeBetweenLives, SoulPurpose, SoulMateConnections, TwinFlameConnections, AngelicGuidance,
SpiritGuideCommunication, AncestorWorship, ShamanicJourneys, LucidDreaming, DreamWalking, AstralTravel,
EthericProjection, RemoteViewing, PsychicShielding, EnergyProtection, ChakraBalancing, AuraCleansing,
MeditationTechniques, VisualizationMethods, MindfulnessPractices, CosmicOrdering, ManifestationTechniques,
LawOfAttraction, VibrationalAlignment, BrainwaveEntrainment, BinauralBeats, IsochronicTones,
SolfeggioFrequencies, ChakraFrequencies, AngelicFrequencies, ReikiSymbols, ReikiAttunement,
SeichimReiki, KarunaReiki, LightarianReiki, PsychicDevelopment, IntuitiveDevelopment,
EmpathicDevelopment, ClairvoyantDevelopment, MediumshipDevelopment, ChannelingDevelopment,
TranceChanneling, ConsciousChanneling, AutomaticWriting, PsychicArt, IntuitiveArt, VisionaryArt,
SpiritualArt, AngelicArt, CosmicArt, GalacticArt, StarseedArt, LightworkerArt, EnergyArt,
HealingArt, MeditationArt, VisualizationArt, MindfulnessArt, ChakraArt, AuraArt, PsychicSymbols,
Runes, Tarot, OracleCards, LenormandCards, IChing, AstrologySymbols, AlchemySymbols,
SacredGeometry, Mandalas, Yantras, Mantras, Mudras, Gemstones, Crystals, EssentialOils,
Aromatherapy, SoundHealing, SolfeggioTones, ChakraHealing, AuraHealing, PranicHealing,
ReconnectiveHealing, QuantumTouch, TherapeuticTouch, HealingTouch, CosmicHealing, AngelicHealing,
SpiritHealing, AncestralHealing, KarmaClearing, PastLifeHealing, InnerChildHealing, SoulHealing
"""

RAW_ASTROGPT = """
Astrology, Horoscopes, BirthChart, NatalChart, SunSign, MoonSign, RisingSign, Ascendant,
Planets, Houses, Aspects, ZodiacSigns, Aries, Taurus, Gemini, Cancer, Leo, Virgo, Libra,
Scorpio, Sagittarius, Capricorn, Aquarius, Pisces, Transits, Progressions, SolarReturn,
LunarReturn, Synastry, CompositeChart, AstroCartography, Midpoints, FixedStars, Chiron, Lilith,
NorthNode, SouthNode, PartOfFortune, Vertex, Retrogrades, Eclipses, PlanetaryCycles, SaturnReturn,
UranusOpposition, ChironReturn, MercuryRetrograde, VenusRetrograde, MarsRetrograde, JupiterCycles,
SaturnCycles, OuterPlanetTransits, AstrologicalAges, AgeOfAquarius, SabianSymbols, AsteroidAstrology,
Ceres, Pallas, Juno, Vesta, Eros, Psyche, KarmaAstrology, EvolutionaryAstrology,
PsychologicalAstrology, MedicalAstrology, FinancialAstrology, MundaneAstrology, ElectionalAstrology,
HoraryAstrology, AstrologySoftware, AstrologyApps, AstrologyReports, DailyHoroscopes,
WeeklyHoroscopes, MonthlyHoroscopes, YearlyHoroscopes, RelationshipAstrology, CareerAstrology,
HealthAstrology, SpiritualAstrology, SoulPurpose, LifePath, DestinyNumbers, AstrologyReadings,
ChartInterpretation, PlanetaryAspects, Conjunction, Opposition, Square, Trine, Sextile, Quincunx,
SemiSextile, SemiSquare, Sesquiquadrate, Biquintile, Quintile, Novile, Septile, AstrologicalHouses,
FirstHouse, SecondHouse, ThirdHouse, FourthHouse, FifthHouse, SixthHouse, SeventhHouse,
EighthHouse, NinthHouse, TenthHouse, EleventhHouse, TwelfthHouse, ZodiacElements, FireSigns,
EarthSigns, AirSigns, WaterSigns, CardinalSigns, FixedSigns, MutableSigns
"""

RAW_STABLEDIFFUSION = """
ImageGeneration, TextToImage, ImageEditing, StyleTransfer, ArtisticStyles, Upscaling, Inpainting,
Outpainting, Watercolor, OilPainting, Impressionism, AbstractArt, PopArt, Cartooning, PixelArt, VectorGraphics,
3DModeling, Rendering, LightingEffects, Shadowing, TextureMapping, PatternGeneration, ColorPalette, MoodBoard,
Composition, Photography, ImageEnhancement, NoiseReduction, ImageRestoration, FaceGeneration, BodyGeneration,
AnimalGeneration, ObjectGeneration, SceneGeneration, LandscapeGeneration, PortraitGeneration, Caricature,
Silhouette, ContourDrawing, GestureDrawing, FigureDrawing, AnatomyStudies, StillLife, FloralPatterns,
GeometricPatterns, Mandala, Kaleidoscope, Fractals, LowPoly, PixelPerfect, Isometric, IconDesign, LogoCreation,
Branding, VisualIdentity, UIComponents, WebDesign, MobileDesign, GraphicDesign, Illustration, Storyboarding,
ComicArt, Manga, Anime, CharacterDesign, ConceptArt, EnvironmentDesign, PropDesign, VehicleDesign, Architecture,
InteriorDesign, ProductDesign, FashionDesign, TextileDesign, PatternDesign, ColorTheory, Typography, Lettering,
Calligraphy, HandLettering, DigitalPainting, MixedMedia, Collage, Photomanipulation, ImageComposite,
DoubleExposure, LongExposure, TimeLapse, Hyperlapse, Cinemagraph, UniversalGeometry, FractalGeometry,
SacredGeometry, GeometricAbstraction, OpArt, KineticArt, LightArt, IntuitionDevelopment, DigitalSculpture,
3DPrinting, VirtualReality, AugmentedReality, MixedReality, PsychicProtection, UIAnimation, MotionGraphics,
VideoProduction, Filmmaking, Screenwriting, Storytelling, EnergyShielding, CharacterAnimation, 3DAnimation,
StopMotion, TraditionalAnimation, ExperimentalAnimation, TelekinesisTraining, GlitchArt, Clairalience
"""

RAW_STOCKADVISOR = """
StockMarketAnalysis, TechnicalAnalysis, FundamentalAnalysis, ChartPatterns, TrendAnalysis, CandlestickPatterns,
SupportResistance, MovingAverages, RelativeStrengthIndex, BollingerBands, IchimokuCloud, PointFigureCharts,
MarketTrends, BullBearMarkets, MarketVolatility, TradingVolume, 17. StockScreener, 18. PortfolioAnalysis,
RiskManagement, Diversification, AssetAllocation, SectorRotation, IndustryAnalysis, CompanyFundamentals,
FinancialStatements, RatioAnalysis, GrowthStocks, ValueStocks, DividendStocks, ETFs, MutualFunds, IndexFunds,
HedgeFunds, PrivateEquity, VentureCapital, IPOs, MergersAcquisitions, MarketNews, EconomicIndicators, GDP,
InflationRate, InterestRates, UnemploymentRate, CentralBanks, FederalReserve, MonetaryPolicy, FiscalPolicy,
StockValuation, DiscountedCashFlow, ComparableAnalysis, precedentTransactions, LeveragedBuyouts, MergerArbitrage,
EventDriven, GlobalMacro, Cryptocurrency, Blockchain, Bitcoin, Ethereum, Altcoins, CryptoTrading, CryptoInvesting,
CryptoMining, CryptoWallets, CryptoExchanges, CryptoLending, CryptoBorrowing, CryptoMargins, CryptoShorting,
CryptoOptions, CryptoFutures, BlockchainDevelopment, SmartContracts, DecentralizedApps, InitialCoinOfferings,
SecurityTokenOfferings, CryptoRegulations, CryptoTaxes, CryptoAudit, CryptoCompliance, RiskAssessment,
PortfolioOptimization, Backtesting, MonteCarloSimulations, ValueAtRisk, ExpectedShortfall, ConditionalValueAtRisk,
DrawdownAnalysis, PortfolioRebalancing, TaxEfficient Investing, EstatePlanning, RetirementPlanning, WealthManagement,
RoboAdvisors, AutomatedInvesting, MicroInvesting, FractionalShares, DollarCostAveraging, MarketTiming, SectorRotation,
StyleBox, FactorBasedInvesting, ESGInvesting, SustainableInvesting, ImpactInvesting, ThematicInvesting, ActiveManagement,
PassiveManagement, QuantitativeAnalysis, QuantitativeTrading, HighFrequencyTrading, AlgorithmicTrading, MachineLearning,
DeepLearning, NeuralNetworks, ReinforcementLearning, PredictiveAnalytics, PrescriptiveAnalytics, StockPrediction, MarketForecasting
"""

RAW_TAROTTALK = """
TarotTalk, TarotReadings, TarotCards, MajorArcana, MinorArcana, Wands, Cups, Swords, Pentacles, Fool, Magician,
HighPriestess, Empress, Emperor, Hierophant, Lovers, Chariot, Strength, Hermit, WheelOfFortune, Justice, HangedMan,
Death, Temperance, Devil, Tower, Star, Moon, Sun, Judgement, World, AceOfWands, TwoOfWands, ThreeOfWands, FourOfWands,
FiveOfWands, SixOfWands, SevenOfWands, EightOfWands, NineOfWands, TenOfWands, PageOfWands, KnightOfWands, QueenOfWands,
KingOfWands, AceOfCups, TwoOfCups, ThreeOfCups, FourOfCups, FiveOfCups, SixOfCups, SevenOfCups, EightOfCups, NineOfCups,
TenOfCups, PageOfCups, KnightOfCups, QueenOfCups, KingOfCups, AceOfSwords, TwoOfSwords, ThreeOfSwords, FourOfSwords,
FiveOfSwords, SixOfSwords, SevenOfSwords, EightOfSwords, NineOfSwords, TenOfSwords, PageOfSwords, KnightOfSwords,
QueenOfSwords, KingOfSwords, AceOfPentacles, TwoOfPentacles, ThreeOfPentacles, FourOfPentacles, FiveOfPentacles,
QueenOfPentacles, KingOfPentacles, TarotSpreads, CelticCross, ThreeCardSpread, PastPresentFuture, AstrologySpread,
RelationshipSpread, CareerSpread, FinanceSpread, HealthSpread, SpiritualSpread, KarmicSpread, PastLifeSpread,
TarotReversals, TarotCombinations, TarotCorrespondences, TarotAstrology, TarotKabbalah, TarotAlchemistry,
TarotMagic, TarotRituals, TarotMeditation, TarotVisulization, TarotAffirmations, TarotJournaling, TarotMeditation,
TarotVisualization, TarotBreathwork, TarotGrounding, TarotProtection, TarotClearing, TarotCharging, TarotConsecration,
TarotBlessing, TarotScrying, TarotAstral, TarotReiki, TarotHealing, TarotReadingsOnline, TarotApps, TarotSoftware, TarotCommunity
"""

RAW_VEDIC = """
VedicAstrology, Jyotish, HinduAstrology, SiderealZodiac, Nakshatras, BharaniNakshatra, PastLifeRegression,
KarmaTheory, KarmicDebt, KarmicCycles, SanchitaKarma, PrarabdhaKarma, RelationshipCompatibility, KriyamanaKarma,
SynastryAnalysis, MarriagePrediction, ChildrenPrediction, CareerPrediction, HealthPrediction, WealthPrediction, Yogas,
Doshas, Gunas, Bhavas, Houses, PlanetaryTransits, Gochara, VimshottariDasha, Ashtakavarga, EnergyShielding,
KalamsarpaYoga, NadiAstrology, NadiDasha, JaiminiAstrology, CharaDasha, MandookDasha, Sudasha, PranaDasha, DehaDasha,
VimshottariMahadasha, Antardashas, Pratyantardasha, Sookshmandasha, KarmicAstrology, DhanaYoga, RajaYoga, GajaKesariYoga,
BudhaAdityaYoga, ShubhaKartariYoga, PapakartariYoga, VesiYoga, VipareetaVesiYoga, UbhayacharaYoga, PushkalaYoga,
MalavyaBhagyaYoga, LakshmiNarayanaYoga, KusumaYoga, SaraswatiYoga, KalatraYoga, PutraYoga, LabhaYoga, KarmaYoga,
SwargaYoga, AyushKarmaYoga, MrityuBhagyaYoga, AyurBhavaYoga, RandhraBhavaYoga, BhavaKarakaYoga, IshtaDevataYoga,
PutraBhagyaYoga, KalatraBhagyaYoga, DhanaBhagyaYoga, KarmaBhagyaYoga, MokshaBhagyaYoga, AtmaKarakaYoga, AmatyaKarakaYoga,
BhratriKarakYoga, MatruKarakYoga, PitruKarakYoga, PutraKarakYoga, KalatraKarakYoga, DhanaKarakYoga, KarmaKarakYoga,
MokshaKarakYoga, AtmaKarakPhalaYoga
"""

RAW_ASTROGPT_PLUS = """
Astrology, ZodiacSigns, StarCharts, BirthCharts, PlanetaryAlignment, CosmicEvents, Astronomy, SpaceExploration,
GalacticStudies, AlienLife, Astrobiology, Astrochemistry, Astroecology, SunSign, MoonSign, Ascendant, PlanetaryTransits,
AstrologicalHouses, Cusps, Aspects, OrbitalPatterns, EclipsePredictions, SolarEclipses, LunarEclipses, PlanetaryRetrogrades,
AstrologicalCycles, SynodicCycles, SiderealCycles, TropicalCycles, VedicAstrology, WesternAstrology, ChineseAstrology,
MayanAstrology, EgyptianAstrology, AstrologicalElements, FireSigns, EarthSigns, AirSigns, WaterSigns, CardinalSigns,
FixedSigns, MutableSigns, AstrologicalQualities, Masculine Signs, Feminine Signs, AstrologicalPolarity, YinYang,
AstrologicalHousesSystems, Placidus, Koch, Campanus, Regiomontanus, Equal, WholeSign, Alcabitius, Morinus, Topocentric,
AstrologicalAspects, Conjunction, Opposition, Square, Trine, Sextile, Quincunx, Semisquare, Sesquiquadrate, Semisextile,
AstrologicalAspectPatterns, T-Square, GrandCross, GrandTrine, Kite, Cradle, Basket, Sling, AstrologicalHileg, PartOfFortune,
PartOfSpirit, Vertex, AstrologicalMidpoints, IntuitionDevelopment, MidpointTheory, Synastry, CompositeCharts, DavisonCharts,
AstrologicalAge, SecondaryProgressions, TertiaryProgressions, MinorProgressions, Transits, SolarArcs, LunarCycles, EclipsesCycles,
PlanetaryCycles, AstrologicalResearch, AstrologicalTheory, HoraryAstrology, ElectionalAstrology, AstrologicalMagic, AstrologicalRituals
"""

RAW_CHATGPT = """
AI, ConversationalAI, NaturalLanguage, DialogueSystems, ChatBot, AICommunication, HumanLikeDialogue, TextGeneration,
LanguageProcessing, SemanticAnalysis, SentimentAnalysis, IntentRecognition, EntityRecognition, TopicModeling, LanguageTranslation,
Summarization, QuestionAnswering, KnowledgeGraphs, OntologyEngineering, TaxonomyCreation, Categorization, Classification, Clustering,
RecommendationSystems, Personalization, UserProfiling, BehavioralAnalysis, EmotionalIntelligence, EmpathyModeling, NaturalLanguageGeneration,
DialogueManagement, ConversationFlow, TurnTaking, ResponseGeneration, ContextualUnderstanding, CommonSenseReasoning, WorldKnowledge,
DomainSpecificKnowledge, EntityLinking, CoreferenceResolution, DependencyParsing, PartOfSpeechTagging, NamedEntityRecognition, SlotFilling,
IntentDetection, SentimentClassification, EmotionDetection, OpinionMining, TextClassification, ClusteringAnalysis, TopicDiscovery, KeywordExtraction,
SummarizationTechniques, ActiveLearning, SemiSupervisedLearning, UnsupervisedLearning, TransferLearning, MultitaskLearning, DomainAdaptation,
ZeroShotLearning, FewShotLearning, HumanEvaluation, UserStudies, A/BTesting, ClickThroughRate, ConversionRate, CustomerSatisfaction, NetPromoterScore,
ReturnOnInvestment, TimeOnPage, BounceRate, EngagementMetrics, SentimentAnalysisTools, TextAnalyticsPlatforms, NaturalLanguageToolkit, MachineLearningLibraries,
DeepLearningFrameworks, NeuralNetworkArchitectures, ModelEvaluationMetrics, PrecisionRecallCurves, ReceiverOperatingCurves, ConfidenceIntervals, CrossValidation,
HyperparameterTuning, ModelSelection, EnsembleMethods, Bagging, Boosting, Stacking, ModelInterpretability, FeatureImportance, PartialDependencePlots,
IndividualConditionalExpectation, LocalInterpretableModelAgnosticExplanations, ModelExplainability, Transparency, Accountability, Fairness, BiasDetection,
BiasMitigation, ModelDebugging, ErrorAnalysis, AblationStudies, AdversarialTesting, RobustnessChecking, EdgeCases, ModelUpdates, OnlineLearning, ContinualLearning,
MultimodalLearning, HumanInTheLoop, ActiveLearning, SemiSupervised, Unsupervised, SelfSupervised, ContrastiveLearning, GraphLearning, ReinforcementLearning,
ImitationLearning, ModelCompression
"""

# ---------------------------
# 4) CLEAN THEM
# ---------------------------

mysticmind_traits      = clean_list(RAW_MYSTICMIND)
astrogpt_traits        = clean_list(RAW_ASTROGPT)
stabldiffusion_traits  = clean_list(RAW_STABLEDIFFUSION)
stockadvisor_traits    = clean_list(RAW_STOCKADVISOR)
tarottalk_traits       = clean_list(RAW_TAROTTALK)
vedicastrology_traits  = clean_list(RAW_VEDIC)
astrogpt_plus_traits   = clean_list(RAW_ASTROGPT_PLUS)
chatgpt_traits         = clean_list(RAW_CHATGPT)

ALL_TRAITS = {
    "mysticmind_traits": mysticmind_traits,
    "astrogpt_traits": astrogpt_traits,
    "stabldiffusion_traits": stabldiffusion_traits,
    "stockadvisor_traits": stockadvisor_traits,
    "tarottalk_traits": tarottalk_traits,
    "vedicastrology_traits": vedicastrology_traits,
    "astrogpt_plus_traits": astrogpt_plus_traits,
    "chatgpt_traits": chatgpt_traits,
}

# write outputs beside this file (…/scripts/)
OUT_DIR = Path(__file__).resolve().parent
write_outputs(ALL_TRAITS, OUT_DIR)

# ---------------------------
# 5) SIMPLE RESPONDER
# ---------------------------

def respond(input_text: str) -> str:
    inputs = tokenizer(input_text, return_tensors="pt").to(device)
    outputs = model.generate(
        **inputs,
        max_length=512,
        num_beams=5,
        early_stopping=True
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

if __name__ == "__main__":
    print("Traits cleaned & saved as traits_clean.py and traits_clean.json.")
    demo = respond("What can you tell me about astral projection?")
    print("\nDEMO RESPONSE:\n", demo)
